### ISSUE TITLE
Local host doesn't work.

### ISSUE THREAD

**Issue by Suleman-Elahi** [pyxel-dev/chaton#1]
I tried installing this on my Linux PC. The UI is shown at localhost:1234 but nothing happens after I click any button. Doesn't create any room or show the popup box to enter room ID.

There is an error as well in the `npm start` command as well.

```
r470:[alice]:~/chaton$ **npm start**

> chaton@0.1.0 start /home/alice/chaton
> parcel src/index.html

Server running at http://localhost:1234 
⚠️  /home/alice/chaton/node_modules/dotenv/lib/main.js:96:41: Cannot statically evaluate fs argument
  94 |   try {
  95 |     // specifying an encoding returns a string instead of a buffer
> 96 |     const parsed = parse(fs.readFileSync(dotenvPath, { encoding }), { debug })
     |                                         ^
  97 | 
  98 |     Object.keys(parsed).forEach(function (key) {
  99 |       if (!Object.prototype.hasOwnProperty.call(process.env, key)) {
✨  Built in 32.57s.
```
![image](https://user-images.githubusercontent.com/24384996/104013562-9e43e400-51d7-11eb-8161-245fa4f1dd35.png)

**Comment by KevinPy** [comment]
Hello,
Do you have create a Firebase application ? If you read .`gitignore`, you see a file `.env` with different values.

Create a file `.env`:
```
FB_API_KEY=xxx
FB_AUTH_DOMAIN=xxx.firebaseapp.com
FB_DATABASE_URL=https://xxx.firebaseio.com
FB_PROJECT_ID=xxx
FB_STORAGE_BUCKET=xxx.appspot.com
FB_MESSAGING_SENDER_ID=xxx
FB_APP_ID=xxx
FB_MEASUREMENT_ID=xxx
```

Also, the warning message on `npm start`, an issue has been opened on ParcelJS: https://github.com/parcel-bundler/parcel/issues/2363. I will fix it

**Comment by Suleman-Elahi** [comment]
Well I am not an expert in these JS apps. I created Firebase App and then copied all the parameters in the .env file. Still I have the same problem. Nothing happens after I click on the buttons on the UI. But I am not seeing the previous warning in the `npm start` command now.

```
r470:[alice]:~/chaton$ npm start

> chaton@0.1.0 start /home/alice/chaton
> parcel src/index.html

Server running at http://localhost:1234 
✨  Built in 5.28s.
```
Here is the env file:

![image](https://user-images.githubusercontent.com/24384996/104017592-63917a00-51de-11eb-89d1-504250dfaa41.png)

**Comment by KevinPy** [comment]
You must have installed `firebase-tools` via `npm`.
- `npm i -g firebase-tools`
- `firebase login`
- `firebase init` or `firebase use --add`
- Select your project, choose `hosting` and `firestore` with CLI prompt
- Multiple files are added into project (`firebase.json`, `firestore`, ...)

Doc => https://firebase.google.com/docs/cli#mac-linux-npm

**Comment by Suleman-Elahi** [comment]
Thanks.
